# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

convolveCpp <- function(a, b) {
    .Call('anRpackage_convolveCpp', PACKAGE = 'anRpackage', a, b)
}

fibonacci <- function(x) {
    .Call('anRpackage_fibonacci', PACKAGE = 'anRpackage', x)
}

rcpp_hello_world <- function() {
    .Call('anRpackage_rcpp_hello_world', PACKAGE = 'anRpackage')
}

